- src/fuzzfetch/fetch.py
without this fix, domfuzz fails as follows:
Traceback (most recent call last):
File "/domfuzz/dom/automation/loopdomfuzz.py", line 261, in <module>
start_runs()
File "/domfuzz/dom/automation/loopdomfuzz.py", line 258, in start_runs
many_timed_runs(None, sps.createWtmpDir(os.getcwdu()), sys.argv[1:], collector, quiet=False)
File "/domfuzz/dom/automation/loopdomfuzz.py", line 61, in many_timed_runs
bc = domInteresting.BrowserConfig(args, collector)
File "/domfuzz/dom/automation/domInteresting.py", line 509, in __init__
self.dirs = FigureOutDirs(getFullPath(browserDir))
File "/domfuzz/dom/automation/domInteresting.py", line 405, in __init__
self.hgRev = downloadedBuildRev(browserDir)
File "/domfuzz/dom/automation/domInteresting.py", line 442, in downloadedBuildRev
for fn in …
> allow domfuzz to work.

- src/fuzzfetch/fetch.py
Rank is not always a useful value. For example on Windows ASan builds is it 0. Using build_id will always be a useful value and it has the benefit of also being human readable. This also makes it easy to tell if you have old builds laying around.
Is there any reason to not switch over? Is there something that requires the current formatting?
> Use build_id instead of rank in directory name

- setup.py
- src/fuzzfetch/fetch.py
This allows getting the latest revision on the command line using a command like:
fuzzfetch --dry-run 2>&1 | sed -n 's/.*> Changeset: \(.*\)/\1/p'
> Add --dry-run to allow checking what task is found without actually downloading it.

- setup.py
- src/fuzzfetch/fetch.py
Example download for Android:
```
$ fuzzfetch --os Android --cpu x86 -d --fuzzing
[2018-09-05 15:24:53] Identified task: https://index.taskcluster.net/v1//task/gecko.v2.mozilla-central.latest.mobile.android-x86-fuzzing-debug
[2018-09-05 15:24:53] > Task ID: GnSdA1bjSECc722LvaQyeQ
[2018-09-05 15:24:53] > Rank: 1536171209
[2018-09-05 15:24:53] > Changeset: e401d1d666005bcf9ccf7fb9f9aa3256b9446544
[2018-09-05 15:24:53] > Build ID: 20180905181329
[2018-09-05 15:24:54] > Downloading: https://queue.taskcluster.net/v1/task/GnSdA1bjSECc722LvaQyeQ/artifacts/public/build/target.apk (42.23MB total)
[2018-09-05 15:24:56] .. downloaded (14.28MB/s)
[2018-09-05 15:24:57] > Downloading: https://queue.taskcluster.net/v1/task/GnSdA1bjSECc722LvaQyeQ/artifacts/public/build/target.crashreporter-symbols.zip …
```
> Cross-platform support (--os/--cpu) and Android

- src/fuzzfetch/fetch.py
This PR adds support for gtests with a tar.gz extension.  If gtests were requested but no "tar.gz" archive found, fall back to older "zip" format.
> Add support for tar.gz gtests

- src/fuzzfetch/extract.py
I assume there is no reason to show the 7z output?
```
...
[2019-11-15 17:05:50] .. extracting
7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18
p7zip Version 9.20 (locale=en_CA.UTF-8,Utf16=on,HugeFiles=on,8 CPUs)
Processing archive: /tmp/fuzzfetch-64vDFf.tar.bz2
Extracting  fuzzfetch-64vDFf.tar
Everything is Ok
Size:       0
Compressed: 71309471
...
```
> Hide 7z output

- setup.cfg
- src/fuzzfetch/fetch.py
Nearest search may fail if start and end boundaries exceed valid range.  This PR locks these boundaries to the earliest/latest available build.
> Ensure nearest ranges use the minimal boundary

- src/fuzzfetch/fetch.py
This PR refactors existing arg parser into an exportable class.  This allows other projects that leverage fuzzfetch to import the argument parsing and sanity checks without having to duplicate it elsewhere.
> Organize argparser in exported class

- src/fuzzfetch/fetch.py
Adds support for autoland builds and fixes a bug in retrieving the pushdate and hash for inbound builds (both use integration/branch).
I didn't include autoland in the tests since we don't test every branch but if you want, I'll add it.
> Add support for autoland builds

- src/fuzzfetch/fetch.py
Noting that the coverage build includes *.gcno is redundant.  Proposed removal to simplify arg output.
> Remove redundant help text

- src/fuzzfetch/fetch.py
> Support fuzzing-debug builds without crashreporter-symbols.zip

- src/fuzzfetch/fetch.py
Creating an HgRevision instance for the release, beta, and esr branches fail due to incorrect path building for hg.mozilla.org.
> Fix hg.mozilla.org path for release, beta, and esr

- src/fuzzfetch/fetch.py
Using a namespace throws with:
```
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/forb1dden/tools/fuzzfetch/src/fuzzfetch/__main__.py", line 9, in <module>
Fetcher.main()
File "/home/forb1dden/tools/fuzzfetch/src/fuzzfetch/fetch.py", line 1279, in main
obj, extract_args = cls.from_args()
File "/home/forb1dden/tools/fuzzfetch/src/fuzzfetch/fetch.py", line 1232, in from_args
if args.branch.startswith("esr"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
> Don't resolve_esr if build is a namespace

- src/fuzzfetch/fetch.py
This is necessary when using an autoland namespace.
```
python -m fuzzfetch --build gecko.v2.autoland.revision.00082591503eb5e57cce27f722b8a45c943c7034.firefox.linux64-asan-opt
[2021-02-10 19:06:11] Identified task: https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/gecko.v2.autoland.revision.00082591503eb5e57cce27f722b8a45c943c7034.firefox.linux64-asan-opt
...
[2021-02-10 19:07:52] Extracted into /home/user/builds/m-?-20200527140754-opt
> Add autoland to branch search regex

- src/fuzzfetch/fetch.py
- tests/test_fetch.py
`--target` now takes more than one arg, eg. `--target firefox js gtest common`
Any target other than `firefox` or `js` is expected to be a test artifact.
Fixes #92 
I still plan to make http head requests for all artifacts before download to fail early if a bad target name is given.
> Add support for downloading more than one artifact from the same build.

- .taskcluster.yml
Otherwise events with many affected files can result in an object too large for Docker to handle as an environment variable.
> [CI] Filter github event to only necessary fields

- src/fuzzfetch/core.py
- src/fuzzfetch/extract.py
- tests/test_extract.py
I had an old branch to profile extraction methods so I could choose the fastest. Rebased and ran, I got the following results:
```
[2022-11-21 14:31:45] profiling 7z:zip
[2022-11-21 14:31:58]  > mean: 66.32ms stdev: 1.2865ms (100 iterations)
[2022-11-21 14:31:58] profiling unzip
[2022-11-21 14:32:16]  > mean: 194.75ms stdev: 2.0681ms (50 iterations)
[2022-11-21 14:32:16] profiling py:zipfile
[2022-11-21 14:32:29]  > mean: 64.43ms stdev: 1.9492ms (100 iterations)
[2022-11-21 14:32:29]
[2022-11-21 14:32:29] profiling tar
[2022-11-21 14:32:42]  > mean: 27.96ms stdev: 0.4993ms (200 iterations)
[2022-11-21 14:32:42] profiling py:tarfile
[2022-11-21 14:32:53]  > mean: 53.34ms stdev: 2.3217ms (100 iterations)
[2022-11-21 14:32:53]
[2022-11-21 14:32:53] profiling 7z:bz2
[2022-11-21 14:33:02]  > …
```
> Add support for lbzip2 and tar

- src/fuzzfetch/args.py
- src/fuzzfetch/core.py
Required refactoring the `extract_zip` and `extract_tar` methods to accept a full URL as `mozharness.zip` isn't prefixed with the typical `target.{path}.zip` suffix.
> Add support for downloading mozharness

- .taskcluster.yml
During recent incident where `release` build was cancelled it was discovered that multiple task graphs are being created:
-    02344790-61f0-11ee-9b3b-bf21df2e33e8 at 2023-10-03 13:23:16.945+00 (action: published)
-    022ef060-61f0-11ee-8808-d2c41dba997b at 2023-10-03 13:23:17.006+00 (action: created)
-    02281290-61f0-11ee-9434-9981115b9963 at 2023-10-03 13:23:17.059+00 (action: released)
each of them resulted in creation of separate task groups: `eAhvf8KjSNW6pcYYjaIPfA`, `Nio-_qsrRcK5OQGH09TygQ`, `TfFA22PTQIWCKQbhHi14qg`
Taskcluster Github service was patched to fix this issue where it shouldn't be cancelling release events at all: https://github.com/taskcluster/taskcluster/pull/6595 
And I think it is also important not to create additional builds for extra release events.
> Include only expected events and actions

- README.md
- src/fuzzfetch/args.py
- src/fuzzfetch/core.py
- src/fuzzfetch/models.py
- tests/mock-firefoxci/api/index/v1/task/gecko.v2.mozilla-central.latest.firefox.linux64-searchfox-debug
- tests/mock-firefoxci/api/queue/v1/task/fcYf8jKOQ9yV6VtZtbFNJQ/artifacts/.get
- tests/mock-firefoxci/api/queue/v1/task/fcYf8jKOQ9yV6VtZtbFNJQ/artifacts/public/build/target.json
- tests/test_fetch.py
> Add support for searchfox data

- src/fuzzfetch/core.py
- src/fuzzfetch/extract.py
- tests/cassettes/test_core/test_extract_build_linux.yaml
- tests/cassettes/test_core/test_extract_build_macos.yaml
- tests/test_extract.py
As per https://bugzilla.mozilla.org/show_bug.cgi?id=1710599, Linux builds will soon be switched from bz2 to xz.  Based on the patch this appears to only apply to the build itself and not other artifacts.
> Add support for xz builds

- README.md
- src/fuzzfetch/args.py
- src/fuzzfetch/core.py
- src/fuzzfetch/models.py
- src/fuzzfetch/utils.py
- tests/test_utils.py
This means you can pass either a BuildID or SourceStamp to get a specific build, or search older/newer builds.
Fixes #94
> Support passing BuildID as a `--build` argument.
